version: "3.9"

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    hostname: searxng
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    depends_on:
      - redis
    environment:
      - SEARXNG_BASE_URL=http://210.208.224.12:8080/
      - BIND_ADDRESS=0.0.0.0:8080
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true

  redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-redis
    hostname: searxng-redis
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    volumes:
      - searxng-redis:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    security_opt:
      - no-new-privileges:true

volumes:
  searxng-redis:
